const $=id=>document.getElementById(id),P=['TR','AR','CO','IN'],colors=['#4361ee','#14a58b','#e69b27','#c25fe1','#42a7c4','#f46a60'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sum=(rs,k)=>rs.reduce((s,r)=>s+(Number(r[k])||0),0),pct=(n,d)=>d?100*n/d:null,fmt=(n,d=1)=>n===null||n===undefined?'—':Number(n).toLocaleString('ru-RU',{maximumFractionDigits:d}),pc=n=>n===null?'—':fmt(n)+'%';
const card=(l,v,n='')=>`<div class="card"><div class="label">${l}</div><div class="value">${v}</div><small>${n}</small></div>`,panel=(title,body)=>`<section class="panel"><h2>${title}</h2>${body}</section>`,note=(s,w=false)=>`<div class="note ${w?'warn':''}">${s}</div>`;
const page=document.body.dataset.page,q=new URLSearchParams(location.search);let tab=0;
const names={index:'Главная · план–факт',pulsation:'Пульсация',retention:'Ретеншен и воронка',late_ftd:'Долёты',reactivation:'Чарн и реактивация',crm:'CRM',projects:'Задачи команды'};
$('nav').innerHTML=Object.entries(names).map(([k,v])=>`<a href="${k}.html">${v}</a>`).join('');
$('title').textContent=names[page];$('stamp').textContent=`Факт по ${DATA.meta.as_of} · история с ${DATA.meta.activity_start}`;
const months=[...new Set([...DATA.meta.months,...(DATA.plans||[]).map(r=>r.month)])].sort().reverse();
$('month').innerHTML='<option value="all">Все месяцы</option>'+months.map(m=>`<option>${m}</option>`).join('');
$('month').value=months.includes(q.get('month'))?q.get('month'):(page==='index'?months[0]:DATA.meta.as_of.slice(0,7));
$('geo').innerHTML='<option value="primary">Основные GEO вместе</option>'+P.map(g=>`<option>${g}</option>`).join('')+'<optgroup label="Другие GEO">'+DATA.meta.geos.filter(g=>!P.includes(g)).map(g=>`<option>${g}</option>`).join('')+'</optgroup><option value="all">Все GEO вместе</option>';
if([...$('geo').options].some(o=>o.value===q.get('geo')))$('geo').value=q.get('geo');
const gg=r=>$('geo').value==='all'||($('geo').value==='primary'?P.includes(r.geo):r.geo===$('geo').value),mm=(r,key='month')=>$('month').value==='all'||r[key]===$('month').value;
const gs=()=> $('geo').value==='primary'?P:$('geo').value==='all'?DATA.meta.geos:[$('geo').value];
function table(head,rows){return `<div class="scroll"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`+(rows.length?'':'<div class="empty">Нет данных для выбранного периода</div>');}
function line(series,{percent=false}={}){series=series.filter(s=>s.values.length);if(!series.length)return '<div class="empty">Нет зрелой базы</div>';const allx=[...new Set(series.flatMap(s=>s.values.map(v=>v[0])))].sort(),vals=series.flatMap(s=>s.values.map(v=>v[1])).filter(v=>v!==null&&Number.isFinite(v));let min=Math.min(0,...vals),max=percent?100:Math.max(1,...vals);const W=1000,H=310,L=65,R=20,T=20,B=45,x=i=>L+i*(W-L-R)/Math.max(1,allx.length-1),y=v=>T+(max-v)/(max-min||1)*(H-T-B);let svg='';for(let i=0;i<=4;i++){let v=min+(max-min)*i/4;svg+=`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#e3e8f0"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end" font-size="12" fill="#69768b">${fmt(v,0)}${percent?'%':''}</text>`;}allx.forEach((v,i)=>{if(i%Math.max(1,Math.ceil(allx.length/10))===0||i===allx.length-1)svg+=`<text x="${x(i)}" y="${H-15}" text-anchor="middle" font-size="11" fill="#69768b">${esc(v)}</text>`;});series.forEach((s,j)=>{let seg=[];const flush=()=>{if(seg.length)svg+=`<polyline points="${seg.join(' ')}" fill="none" stroke="${colors[j%colors.length]}" stroke-width="2.5"/>`;seg=[];};s.values.forEach(([a,v])=>{if(v===null){flush();return;}const xx=x(allx.indexOf(a)),yy=y(v);seg.push(`${xx},${yy}`);svg+=`<circle cx="${xx}" cy="${yy}" r="3" fill="${colors[j%colors.length]}"><title>${esc(s.name)} · ${a}: ${fmt(v)}${percent?'%':''}</title></circle>`;});flush();});return `<svg viewBox="0 0 ${W} ${H}" role="img">${svg}</svg><div class="legend">${series.map((s,i)=>`<span><i class="dot" style="background:${colors[i%colors.length]}"></i>${esc(s.name)}</span>`).join('')}</div>`;}
function bars(rows){let max=Math.max(1,...rows.map(r=>r[1]||0));return '<div class="bars">'+rows.map(([label,n,detail])=>`<div class="row"><span>${label}</span><div class="bar"><i style="width:${100*(n||0)/max}%"></i></div><span>${fmt(n)} ${detail||''}</span></div>`).join('')+'</div>';}
function group(rs,key){return Object.groupBy?Object.groupBy(rs,r=>r[key]):rs.reduce((o,r)=>((o[r[key]]??=[]).push(r),o),{});}
function trend(rs,keys){const by=group(rs,'date');return line(keys.map(([k,name])=>({name,values:Object.keys(by).sort().map(d=>[d,sum(by[d],k)])})));}
function tabs(labels){$('tabs').innerHTML=labels.map((t,i)=>`<button class="${tab===i?'on':''}" onclick="tab=${i};render()">${t}</button>`).join('');}
function related(flow='welcome'){return `<p><a href="crm.html?flow=${flow}&geo=${encodeURIComponent($('geo').value)}&month=${$('month').value}">Связанные CRM-коммуникации →</a> <small>макет, данные не подключены</small></p>`;}
function pulse(){tabs(['Обзор','Игроки и чарн','Бонусы']);const rs=DATA.daily.filter(r=>gg(r)&&mm({month:r.date.slice(0,7)}));let html=note('Активность = ставка или депозит. Выводов средств в новых данных нет. Финансовые суммы при пропусках показаны как известная часть.',true);if(tab===0){html+='<div class="cards">'+card('Депозиты, USD',fmt(sum(rs,'deposit_sum_usd')))+card('Количество депозитов',fmt(sum(rs,'deposit_cnt'),0))+card('GGR, USD',fmt(sum(rs,'ggr_usd')))+card('NGR, USD',fmt(sum(rs,'ngr_usd')))+card('Оборот, USD',fmt(sum(rs,'turnover_usd')))+card('Ставки',fmt(sum(rs,'bet_cnt'),0))+card('Bonus cost, USD',fmt(sum(rs,'bonus_cost_usd')))+card('Строк с пропусками финансов',fmt(sum(rs,'financial_missing'),0))+'</div>';html+=panel('Динамика экономики',trend(rs,[['deposit_sum_usd','Депозиты'],['ggr_usd','GGR'],['ngr_usd','NGR']]));html+=panel('По дням',table(['Дата','GEO','Депозиты, USD','Депозиторы за день','Ставки','Оборот','GGR','Бонусы','NGR','Пропуски'],rs.slice().reverse().map(r=>[r.date,r.geo,...['deposit_sum_usd','depositors','bet_cnt','turnover_usd','ggr_usd','bonus_cost_usd','ngr_usd','financial_missing'].map(k=>fmt(r[k]))])));}
if(tab===1){const months=DATA.monthly.filter(r=>gg(r)&&mm(r));html+='<div class="cards">'+card('Регистрации',fmt(sum(rs,'registrations'),0),'Полный реестр с '+DATA.meta.full_registry_from)+card('FTD',fmt(sum(rs,'ftd'),0))+card('Возвраты после 8+ дней',fmt(sum(rs,'reactivated'),0),'События возврата, не уникальные за период')+card('Новые активные в день регистрации',fmt(sum(rs,'new_reg'),0))+'</div>';html+=panel('Баланс активной базы',trend(rs,[['active','Активные'],['first_seen','Первая наблюдаемая активность'],['continuing','Активны и вчера'],['return_short','Возврат после 1–7 дней'],['reactivated','Возврат после 8+ дней']]));html+=note('Разложение DAU: первая наблюдаемая активность + активны вчера + возврат после 1–7 дней + возврат после 8+ дней. Первая наблюдаемая активность без LAG не всегда первая в жизни; известные прошлые активности из LAG учтены в возвратах.');html+=panel('Неактивные 8+ полных дней на конец дня',trend(rs,[['churn_close','Чарн 8+ дней']]));html+=panel('Уникальные активные по месяцам',table(['Месяц','GEO','MAU','Активных дней на игрока'],months.map(r=>[r.month,r.geo,fmt(r.mau,0),fmt(r.active_days/r.mau)])));html+=related('reactivation');}
if(tab===2){const b=DATA.bonuses.filter(r=>gg(r)&&mm(r));if($('month').value!=='all'&&$('month').value<'2026-04')return note('Детализация бонусов доступна только с апреля 2026.');html+=note('Детализация выдач доступна с апреля 2026. Переведённая сумма ниже — текущее состояние бонусов месяца выдачи, а не расходы этого месяца. Для расходов используйте Bonus cost из metrics.');html+='<div class="cards">'+card('Выдано бонусов',fmt(sum(b,'issued'),0))+card('Из них переведены',fmt(sum(b,'transferred'),0))+card('Сумма переводов этих выдач',fmt(sum(b,'transferred_value')))+card('Выдано фриспинов',fmt(sum(b,'freespins'),0))+'</div>';html+=panel('Бонусы по месяцу выдачи',table(['Месяц','GEO','Тип','Статус','Выдано','Переведены','Сумма переводов','Фриспины'],b.map(r=>[r.month,r.geo,esc(r.bonus_type_name),esc(r.given_bonus_state_name),fmt(r.issued),fmt(r.transferred),fmt(r.transferred_value),fmt(r.freespins)])));}return html;}
function retention(){tabs(['Линия ретеншена','Интервалы и когорты','Депозитная воронка']);let html='';if(tab===0){html+=`<div class="filters"><label>Старт / возврат<select id="anchor" onchange="updateCurve()"><option value="bet">Первая ставка → ставка</option><option value="ftd">FTD → ставка или депозит</option></select></label><label>Метрика<select id="kind" onchange="updateCurve()"><option value="rolling">Return On or After</option><option value="exact">Return On · точно в день N</option></select></label><label>Зрелость базы<select id="maturity" onchange="updateCurve()"><option value="mature_day">Зрелые к дню N</option><option value="mature30">Единая зрелая D30 база</option></select></label></div>`;html+=note('Месяц сверху — месяц первого события. Return On or After = активность на Dn или позже до конца выгрузки. История после D30 учитывается. Return On = активность ровно в календарный Dn.');html+=note('В Amplitude на скрине 24-часовые окна и Any money bet. Здесь доступны календарные даты и ставки из metrics; состав ставок (real / bonus) требует подтверждения SQL. Для старта от ставки берём регистрации внутри истории, чтобы не выдать первую наблюдаемую ставку старого игрока за первую в жизни.',true);html+='<div id="curve"></div>'+related();}
if(tab===1){const rs=DATA.cohorts.filter(r=>gg(r)&&mm(r));html+=note('Месяц сверху — месяц регистрации. Верифицированный = подтверждён email ИЛИ SMS, не KYC. Интервалы считаются от FTD; знаменатель каждого интервала — FTD с полностью завершённым окном.');html+=note(DATA.meta.registry_note+' Регистрации раньше '+DATA.meta.full_registry_from+' неполные.',true);html+='<div class="cards">'+card('Регистрации',fmt(sum(rs,'regs'),0))+card('FTD',fmt(sum(rs,'ftd'),0),pc(pct(sum(rs,'ftd'),sum(rs,'regs')))+' от регистраций')+card('Подтверждён контакт',fmt(sum(rs,'verified'),0),pc(pct(sum(rs,'verified'),sum(rs,'regs'))))+card('Долётчики',fmt(sum(rs,'late'),0))+'</div>';html+=panel('Возврат по интервалам после FTD',bars([3,7,14,30].map((w,i)=>[['D1–3','D4–7','D8–14','D15–30'][i],pct(sum(rs,'r'+w),sum(rs,'b'+w)),`% · ${fmt(sum(rs,'r'+w),0)} / ${fmt(sum(rs,'b'+w),0)}`])));html+=panel('Когорты месяца регистрации',cohortTable(rs));html+=panel('Rolling retention по тем же когортам',table(['Когорта','GEO','D3+','D7+','D14+','D30+'],rs.map(r=>[r.month,r.geo,...[3,7,14,30].map(w=>pc(pct(r['roll'+w],r['b'+w])))])));html+=related();}
if(tab===2)html+=funnelView(DATA.funnel.filter(r=>gg(r)&&mm(r)));
return html;}
function cohortTable(rs){return table(['Когорта','GEO','Реги','FTD','FTD %','Вериф.','Вериф. %','D1–3 кол. / база','D1–3 %','D4–7 кол. / база','D4–7 %','D8–14 кол. / база','D8–14 %','D15–30 кол. / база','D15–30 %'],rs.slice().sort((a,b)=>b.month.localeCompare(a.month)||P.indexOf(a.geo)-P.indexOf(b.geo)).map(r=>[r.month,r.geo,fmt(r.regs,0),fmt(r.ftd,0),pc(pct(r.ftd,r.regs)),fmt(r.verified,0),pc(pct(r.verified,r.regs)),...[3,7,14,30].flatMap(w=>[`${fmt(r['r'+w],0)} / ${fmt(r['b'+w],0)}`,pc(pct(r['r'+w],r['b'+w]))])]));}
function updateCurve(){const anchor=$('anchor').value,kind=$('kind').value,mode=$('maturity').value;const rs=DATA.curves.filter(r=>gg(r)&&mm(r,'anchor_month')&&r.anchor===anchor&&r.mode===mode),series=gs().map(g=>({name:g,values:Array.from({length:31},(_,d)=>{const a=rs.filter(r=>r.geo===g&&r.day===d);return [String(d).padStart(2,'0'),pct(sum(a,kind),sum(a,'base'))];})}));$('curve').innerHTML=panel('Ретеншен по GEO · D0–D30',line(series,{percent:true}))+panel('Числитель и зрелая база',table(['День',...gs().map(g=>g+' · % (вернулись / база)')],Array.from({length:31},(_,d)=>['D'+d,...gs().map(g=>{let a=rs.filter(r=>r.day===d&&r.geo===g);return `${pc(pct(sum(a,kind),sum(a,'base')))} (${fmt(sum(a,kind),0)} / ${fmt(sum(a,'base'),0)})`})])));}
function funnelView(rs){window.currentFunnel=rs;return note('Месяц сверху — месяц FTD. Для сравнения когорт используется одинаковое окно после FTD. Доли от FTD и переходы между ступенями доступны одновременно.')+`<div class="filters"><label>Окно после FTD<select id="fw" onchange="updateFunnel()"><option value="7">D0–D7 · зрелые D7</option><option value="30">D0–D30 · зрелые D30</option></select></label></div><div id="funnel"></div>`+['dep1_2','dep2_3','dep3_5','dep5_8'].map(related).join('');}
function updateFunnel(){const rs=window.currentFunnel,w=$('fw').value,ks=[1,2,3,5,8],base=sum(rs,'base'+w),nums=ks.map(k=>sum(rs,`d${w}_${k}`));$('funnel').innerHTML='<div class="cards">'+card('Зрелая FTD-база',fmt(base,0))+card('Средние активные дни',fmt(base?sum(rs,'active'+w)/base:null),'D0–D'+w)+card('2+ / FTD',pc(pct(nums[1],base)))+card('8+ / FTD',pc(pct(nums[4],base)))+'</div>'+panel('Воронка депозитов',bars(ks.map((k,i)=>[k+'+ депозитов',nums[i],pc(pct(nums[i],base))+' от FTD'])))+panel('Общая конверсия и переходы',table(['Ступень','Игроков','% от FTD','% от предыдущей ступени','Потеря между ступенями'],ks.map((k,i)=>[k+'+',fmt(nums[i],0),pc(pct(nums[i],base)),i?pc(pct(nums[i],nums[i-1])):'—',i?fmt(nums[i-1]-nums[i],0):'—'])));}
function reactivation(){tabs(['Обзор','Дневная реактивация','База чарна']);const rs=DATA.reactivation.filter(r=>gg(r)&&mm({month:r.date.slice(0,7)})),dates=[...new Set(rs.map(r=>r.date))].sort(),last=dates.at(-1),snap=rs.filter(r=>r.date===last),ch=rs.filter(r=>r.bucket>=1);let html=note('Чарн в этом отчёте: 8+ полных дней без ставок и депозитов. 1–7 дней показаны отдельно как короткая пауза. Например: активность 1 сентября, возврат 10 сентября → 8 полных неактивных дней, категория 8–14.');html+=note('База на начало дня включает тех, кто вернётся сегодня. Первый наблюдаемый активный день без известной предыдущей активности не является реактивацией. LAG восстановил предыдущую активность для '+DATA.meta.lag_seed_users+' игроков до начала истории. Игроки без событий за весь период могут отсутствовать: показатели относятся к наблюдаемой базе.',true);
if(tab===0){html+='<div class="cards">'+card('Чарн 8+ на конец периода',fmt(sum(snap.filter(r=>r.bucket>=1),'closing'),0),last||'нет данных')+card('Возвраты после 8+ дней',fmt(sum(ch,'returned'),0),'События возврата за период')+card('Дневная частота реактивации',pc(pct(sum(ch,'returned'),sum(ch,'base'))),'Возвраты / сумма дневных баз')+card('Короткие возвраты 1–7',fmt(sum(rs.filter(r=>r.bucket===0),'returned'),0))+'</div>';html+=panel('Неактивная база на конец периода',bars(DATA.meta.buckets.map((label,i)=>[label,sum(snap.filter(r=>r.bucket===i),'closing')])));html+=panel('Возвраты по категориям',reactSummary(rs));html+=panel('Возвраты после 8+ дней по датам',trend(ch,[['returned','Реактивации']]));html+=related('reactivation');}
if(tab===1){html+=panel('Доля вернувшихся из категории за день',line(DATA.meta.buckets.map((name,b)=>({name,values:dates.map(d=>{const a=rs.filter(r=>r.date===d&&r.bucket===b);return[d,pct(sum(a,'returned'),sum(a,'base'))];})})),{percent:true}));html+=note('За период: Σ возвратов / Σ дневных баз. Это средневзвешенная дневная частота, а не доля уникальных вернувшихся за месяц. Один игрок может вернуться несколько раз.');html+=panel('Дневные базы и возвраты',table(['Дата','GEO','Категория','На начало дня','Вернулись','Возврат %','На конец дня'],rs.slice().reverse().map(r=>[r.date,r.geo,DATA.meta.buckets[r.bucket],fmt(r.base,0),fmt(r.returned,0),pc(pct(r.returned,r.base)),fmt(r.closing,0)])));}
if(tab===2){html+=panel('Размер категорий по дням · конец дня',line(DATA.meta.buckets.map((name,b)=>({name,values:dates.map(d=>[d,sum(rs.filter(r=>r.date===d&&r.bucket===b),'closing')])}))));html+=panel('Структура по GEO на '+(last||'—'),table(['GEO',...DATA.meta.buckets],gs().map(g=>[g,...DATA.meta.buckets.map((_,b)=>fmt(sum(snap.filter(r=>r.geo===g&&r.bucket===b),'closing'),0))])));html+=note('Месячные категории заданы фиксированными днями: 31–60, 61–90, 91–180 и 181+. Последний профиль last_activity_date не используется для восстановления прошлых состояний — это привело бы к утечке будущего.');}return html;}
function reactSummary(rs){return table(['Категория','Возвратов','Сумма дневных баз','Средневзвешенный дневной %'],DATA.meta.buckets.map((b,i)=>{const a=rs.filter(r=>r.bucket===i);return[b,fmt(sum(a,'returned'),0),fmt(sum(a,'base'),0),pc(pct(sum(a,'returned'),sum(a,'base')))];}));}
function late(){tabs(['План–факт','Когорты и задержка','Депозиты и экономика']);const rs=DATA.late.filter(r=>gg(r)&&mm(r));let html=note('Долётчик: месяц первого депозита позже месяца регистрации. Месяц сверху — месяц FTD.');if(tab===0){html+=planTable((DATA.plans||[]).filter(r=>r.section==='late_ftd'&&gg(r)&&mm(r)));if($('month').value!=='all'&&$('month').value>DATA.meta.as_of.slice(0,7))return html+note('Факт за выбранный месяц пока отсутствует.');html+='<div class="cards">'+card('Долётчики',fmt(sum(rs,'n'),0))+card('Средняя задержка, дней',fmt(sum(rs,'n')?sum(rs,'delay_sum')/sum(rs,'n'):null))+card('Сумма первых депозитов',fmt(sum(rs,'ftd_sum')))+card('NGR D0–D30',fmt(sum(rs,'ngr_usd')),'Только зрелые D30')+'</div>';const by=group(DATA.late.filter(gg),'month');html+=panel('Долёты по месяцам FTD',line([{name:'Долётчики',values:Object.keys(by).sort().map(m=>[m,sum(by[m],'n')])}]));}
if(tab===1){html+=panel('Задержка от регистрации до FTD',bars(DATA.meta.buckets.map((b,i)=>[b,sum(rs,'lag'+i)])));html+=panel('Когорты долётчиков',table(['Месяц FTD','GEO','Рег. когорта','Игроки','Средняя задержка','Первые депозиты USD'],rs.map(r=>[r.month,r.geo,r.reg_month,fmt(r.n,0),fmt(r.delay_sum/r.n),fmt(r.ftd_sum)])));}
if(tab===2){html+=funnelView(rs);html+=panel('Экономика D0–D30 · зрелые когорты',table(['Месяц FTD','GEO','Рег. когорта','Зрелые D30','GGR','Bonus cost','NGR'],rs.map(r=>[r.month,r.geo,r.reg_month,fmt(r.base30),fmt(r.ggr_usd),fmt(r.bonus_cost_usd),fmt(r.ngr_usd)])));}return html;}
function actual(p){if(p.month>DATA.meta.as_of.slice(0,7))return null;const rows=(p.section==='late_ftd'?DATA.late:DATA.funnel).filter(r=>r.month===p.month&&r.geo===p.geo);if(p.metric==='late_ftd_count')return sum(rows,'n');if(p.metric==='retention_d3_plus')return pct(sum(rows,'roll3'),sum(rows,'b3'));const a=(DATA.manual||[]).find(r=>r.month===p.month&&r.geo===p.geo&&r.metric===p.metric);return a&&a.actual!==''?Number(a.actual):null;}
function previousMonth(month){const [y,m]=month.split('-').map(Number);return m===1?`${y-1}-12`:`${y}-${String(m-1).padStart(2,'0')}`;}
function planTable(plans){const val=(v,p)=>fmt(v)+(p.unit==='percent'&&v!==null?'%':'');return panel('План–факт',table(['Месяц','GEO','Показатель','Пред. месяц','План пред. месяца','Факт пред. месяца','Текущий план','Текущий факт','Выполнение'],plans.map(p=>{let a=actual(p),t=p.target===''?null:Number(p.target),r=a===null?null:pct(a,t);const prev=previousMonth(p.month),prior=(DATA.plans||[]).find(x=>x.month===prev&&x.section===p.section&&x.geo===p.geo&&x.metric===p.metric),pt=prior&&prior.target!==''?Number(prior.target):null;let pa=actual({...p,month:prev});if(pa===null&&p.previous_month!==undefined&&p.previous_month!=='')pa=Number(p.previous_month);let color=r===null?'#f1f3f7':`hsl(${Math.min(120,Math.max(0,r*1.2))},75%,82%)`;return[p.month,p.geo,`<a href="${p.section==='home'?'index':p.section}.html?month=${p.month}&geo=${p.geo}">${esc(p.label)}</a>`,prev,val(pt,p),val(pa,p),val(t,p),val(a,p),`<span style="display:block;padding:5px;border-radius:5px;background:${color}">${pc(r)}</span>`];})));}
function home(){tabs([]);let plans=(DATA.plans||[]).filter(mm);let html=note('Общий срез факта: '+DATA.meta.as_of+'. В таблице рядом показаны план и факт выбранного и предыдущего месяца. Факт октября пока отсутствует. Цели D3+ retention на октябрь: TR 60%, AR/CO 40%, IN 30%. «—» означает отсутствие факта или плана, а не ноль.');html+=planTable(plans.filter(r=>P.includes(r.geo)&&gg(r)));html+='<details><summary>Общие цели команды</summary>'+planTable(plans.filter(r=>r.geo==='ALL'))+'</details>';html+='<details><summary>Другие GEO</summary>'+planTable(plans.filter(r=>!P.includes(r.geo)&&r.geo!=='ALL'&&gg(r)))+'</details>';html+=panel('Сильные изменения к предыдущему месяцу',alerts());html+=panel('Разделы',Object.entries(names).filter(([k])=>k!=='index').map(([k,v])=>`<p><a href="${k}.html">${v} →</a></p>`).join(''));html+=panel('О данных и правилах расчёта',DATA.meta.warnings.map(x=>`<p>${esc(x)}</p>`).join(''));return html;}
function alerts(){let month=$('month').value;if(month==='all'||month>DATA.meta.as_of.slice(0,7))return '<p>Выберите месяц с данными. Отсутствие факта не считается падением.</p>';const prev=new Date(month+'-15T12:00:00Z');prev.setUTCMonth(prev.getUTCMonth()-1);const pm=prev.toISOString().slice(0,7);let found=[];for(const geo of gs()){for(const [n,b,label,w] of [['dep2','base7','Конверсия FTD → 2 деп. D7',7],['dep3','dep2','Переход 2 → 3 деп. D7',7],['r3','b3','Возврат D1–3 после FTD',3]]){const cutoff=new Date(DATA.meta.as_of+'T00:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-w);const days=Math.min(new Date(month.slice(0,4),Number(month.slice(5)),0).getDate(),new Date(pm.slice(0,4),Number(pm.slice(5)),0).getDate(),cutoff.toISOString().slice(0,7)===month?cutoff.getUTCDate():31);const now=DATA.alerts.filter(r=>r.geo===geo&&r.month===month&&Number(r.date.slice(8))<=days),old=DATA.alerts.filter(r=>r.geo===geo&&r.month===pm&&Number(r.date.slice(8))<=days);let nb=sum(now,b),ob=sum(old,b);if(nb<100||ob<100)continue;let a=pct(sum(now,n),nb),o=pct(sum(old,n),ob);if(Math.abs(a-o)>=5)found.push(`<div class="alert">${geo} · ${label}: ${pc(o)} → ${pc(a)} (${fmt(a-o)} п.п.)<br><small>Дни FTD 1–${days}; база ${fmt(ob,0)} → ${fmt(nb,0)}.</small> <a href="retention.html?month=${month}&geo=${geo}">Открыть →</a></div>`);}const day=Math.min(Number(DATA.meta.as_of.slice(8)),new Date(pm.slice(0,4),Number(pm.slice(5)),0).getDate());const daily=DATA.daily.filter(r=>r.geo===geo&&Number(r.date.slice(8))<=day);for(const [k,label] of [['deposit_sum_usd','Сумма депозитов'],['ngr_usd','NGR'],['reactivated','События реактивации 8+']]){let a=sum(daily.filter(r=>r.date.startsWith(month)),k),o=sum(daily.filter(r=>r.date.startsWith(pm)),k);if(Math.abs(o)>=30&&Math.abs(a-o)/Math.abs(o)>=.2)found.push(`<div class="alert">${geo} · ${label}: ${fmt(o)} → ${fmt(a)} (${fmt(100*(a-o)/Math.abs(o))}%) · дни 1–${day}. <a href="${k==='reactivated'?'reactivation':'pulsation'}.html?month=${month}&geo=${geo}">Открыть →</a></div>`);}}
return note('Конверсии: 5 п.п., база ≥100 в обоих месяцах; одинаковые дни FTD и зрелые фиксированные окна. Суммы / возвраты: 20%, предыдущая величина ≥30, одинаковые дни месяца. Rolling retention не участвует в алертах. Сигналы не доказывают эффект CRM.')+(found.join('')||'<p>Сильных изменений на достаточной базе нет либо нет сопоставимой базы.</p>');}
function render(){if(page!=='index'&&page!=='late_ftd'&&$('month').value!=='all'&&$('month').value>DATA.meta.as_of.slice(0,7)){tabs([]);$('content').innerHTML=note('За выбранный месяц данные ещё не поступили. Последний день факта: '+DATA.meta.as_of,true);return;}$('content').innerHTML=({index:home,pulsation:pulse,retention,late_ftd:late,reactivation}[page]||home)();if($('curve'))updateCurve();if($('funnel'))updateFunnel();}
$('month').onchange=render;$('geo').onchange=render;
$('download').onclick=()=>{let ts=[...document.querySelectorAll('#content table')];if(!ts.length)return;const text=ts.map(t=>[...t.rows].map(r=>[...r.cells].map(c=>'"'+c.innerText.replace(/"/g,'""')+'"').join(';')).join('\r\n')).join('\r\n\r\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.download=page+'.csv';a.click();URL.revokeObjectURL(a.href);};
render();
